package com.ep.genpro.sign;

import java.util.HashSet;
import java.util.Set;

public class CSharpSign {
	private static CSharpSign instance = new CSharpSign();

	private CSharpSign() {
	}

	public static CSharpSign getInstance() {
		return instance;
	}

	public final String[] Tab = new String[] { "\t", "\t\t", "\t\t\t",
			"\t\t\t\t", "\t\t\t\t\t", "\t\t\t\t\t\t", "\t\t\t\t\t\t\t" };
	public final String Comment = "//";
	public final String Package = "namespace ";
	public final String Import = "using ";
	public final String[] Using = new String[] { Import + "com.ep.stream;",
			Import + "System.Collections.Generic;", Import + "System;",
			Import + "System.Text;" };

	// Import + "UnityEngine;" };
	public final String Public = "public ";
	public final String InnerClassImp = " Data : IMarshal";
	public final String InnerClass = " Data";
	public final String Protected = "protected ";
	public final String Private = "private ";
	public final String Interface = "interface ";
	public final String Class = "class ";
	public final String Extends = ": ";
	public final String Implements = ": ";
	public final String Imarshal = "IMarshal ";
	// public final String Iprotocol = "MonoBehaviour, IProtocol";
	public final String Iprotocol = " IProtocol";

	public final String ProtocolRequestBase = " ProtocolRequestBase";
	public final String ProtocolResponseBase = " ProtocolResponseBase";

	public final String Final = "const ";
	public final String ReadOnly = "readonly ";
	public final String Static = "static ";
	public final String Super = "super";
	public final String Return = "return ";
	public final String If = "if";
	public final String Override = "override ";
	public final String True = "true";
	public final String False = "false";
	public final String Instanceof = "is ";
	public final String Pos_Bean_Interface = "bean";
	public final String Pos_Bean_Class = "bean._";
	public final String Pos_table = "table";
	public final String Pos_octetsStream = "OctetsStream";
	public final String Pos_marshalException = "MarshalException";
	public final String Pos_java_container = "";
	public final String OS_Parameter = "_os_";
	public final String OBJECT_Parameter = "_o_";
	public final String DECLARE_MARSHAL = Public
			+ "OctetsStream Marshal(OctetsStream " + OS_Parameter + ")";

	//	public final String DECLARE_MARSHAL = Public + "OctetsStream Marshal()";
	//	public final String DECLARE_MARSHAL_WITH_PARAMS = Public
	//			+ "OctetsStream Marshal(OctetsStream " + OS_Parameter + ")";

	public final String DECLARE_UNMARSHAL = Public
			+ "OctetsStream Unmarshal(OctetsStream " + OS_Parameter + ")";

	public final String DECLARE_GETDATA = Public + "Data GetData()";

	public final String DECLARE_TOBYTES = Public + "byte[] ToBytes()";

	public final String DECLARE_PARSEFROM = Public
			+ "void ParseFrom(byte[] stream)";

	public final String DECLARE_EQUALS = Public
			+ "override bool Equals(object " + OBJECT_Parameter + ")";
	public final String DECLARE_HASHCODE = Public
			+ "override int GetHashCode()";

	public final String DECLARE_TOSTRING = Public
			+ "override string ToString()";

	public final String DECLARE_TOSTRING0 = Public
			+ "string ToString(int depth)";

	public final String Bean_Interface_Extends = " " + Extends + "Bean";
	public final String Bean_Class_Extends = " " + Extends + "ABean";
	public final String SYS_Tables = "_Tables";
	public final String SYS_Factory = "Factory";
	public final String Pos_Protocol_bean = "bean";
	public final String Protocol_Reserve_Begin = Tab[1]
			+ "//Process Code Section Begin";
	public final String Protocol_Reserve_End = Tab[1]
			+ "//Process Code Section End";
	public final String DECLARE_NO_MODIFY = "//This File Is Generated By protocol Generator, Do Not Modify.";
	public static String CharSet = "UTF-16LE";
	@SuppressWarnings("serial")
	public final Set<String> nameSet = new HashSet<String>() {
		{
			add("protocols");
			add("Offset");
			add("Namespace");
			add("Bean");
			add("KBean");
			add("variable");
			add("Protocol");
			add("Import");
		}
	};
}
