package com.ep.genpro.sign;

import java.util.HashSet;
import java.util.Set;

public class JavaSign {
	private static JavaSign _ = new JavaSign();

	private JavaSign() {
	}

	public static JavaSign getInstance() {
		return _;
	}

	//所有引用的对象路径
	public final String[] ObjPath = new String[] { "com.ep.stream.Protocol",
			"com.ep.stream.Marshal", "com.ep.stream.OctetsStream",
			"com.ep.stream.MarshalException", "com.ep.stream.Octets" };

	public final String[] Tab = new String[] { "", "\t", "\t\t", "\t\t\t",
			"\t\t\t\t", "\t\t\t\t\t", "\t\t\t\t\t\t" };
	public final String Comment = "//";
	public final String Package = "package ";
	public final String Import = "import ";
	public final String[] Using = new String[] { Import + ObjPath[2] + ";",
			Import + ObjPath[3] + ";" };

	public final String Public = "public ";
	public final String Protected = "protected ";
	public final String Private = "private ";
	public final String Interface = "interface ";
	public final String Class = "class ";
	public final String Extends = "extends ";
	public final String Implements = "implements ";
	public final String Final = "final ";
	public final String Static = "static ";
	public final String Super = "super";
	public final String Return = "return ";
	public final String If = "if";
	public final String Override = "@Override";
	public final String True = "true";
	public final String False = "false";
	public final String Instanceof = "instanceof ";
	public final String Pos_Bean_Interface = "bean";
	public final String Pos_Bean_Class = "bean._";
	public final String Pos_table = "table";
	public final String Pos_octetsStream = "";
	public final String Pos_marshalException = "";

	public final String Pos_java_container = "java.util.";
	public final String OS_Parameter = "_os_";
	public final String OBJECT_Parameter = "_o_";
	public final String DECLARE_MARSHAL = Public
			+ "OctetsStream marshal(OctetsStream " + OS_Parameter + ")";
	public final String DECLARE_UNMARSHAL = Public
			+ "OctetsStream unmarshal(OctetsStream " + OS_Parameter
			+ ") throws MarshalException";
	public final String DECLARE_EQUALS = Public + Final
			+ "boolean equals(Object " + OBJECT_Parameter + ")";
	public final String DECLARE_HASHCODE = Public + Final + "int hashCode()";

	public final String DECLARE_TOSTRING = Public + Final + "String toString()";
	public final String DECLARE_TOSTRING0 = Public + Final
			+ "String toString(int depth)";

	public final String Bean_Interface_Extends = " " + Extends + "Bean";
	public final String Bean_Class_Extends = " " + Extends + "ABean";
	public final String SYS_Tables = "_Tables";
	public final String SYS_Factory = "Factory";
	public final String Pos_Protocol_bean = "bean";
	public final String Protocol_Reserve_Begin = Tab[1]
			+ "//Process Code Section Begin";
	public final String Protocol_Reserve_End = Tab[1]
			+ "//Process Code Section End";
	public final String DECLARE_NO_MODIFY = "//This File Is Generated By DB Generator, Do Not Modify.";
	public static String CharSet = "UTF-16LE";

	@SuppressWarnings("serial")
	public final Set<String> nameSet = new HashSet<String>() {
		{
			add("protocols");
			add("Offset");
			add("Namespace");
			add("Bean");
			add("KBean");
			add("variable");
			add("Protocol");
			add("Import");
		}
	};
}
